// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sasheco.Infrastructure.Data;

#nullable disable

namespace Sasheco.Infrastructure.Migrations
{
    [DbContext(typeof(SashecoDbContext))]
    [Migration("20260808075623_AddContractTerms")]
    partial class AddContractTerms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sasheco.Domain.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ApprovalAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.ToTable("ApprovalAttachments");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApprovalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("UserId");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TermsAndConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VendorId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ContractItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractItems");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ContractTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractTerms");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.DrawingAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("DrawingAttachments");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.FinanceMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinanceMilestones");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.FinanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinanceTransactions");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            DescriptionAr = "عرض المواقع",
                            DescriptionEn = "View Sites",
                            NameAr = "عرض المواقع",
                            NameEn = "ViewSites"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            DescriptionAr = "إدارة المواقع",
                            DescriptionEn = "Manage Sites",
                            NameAr = "إدارة المواقع",
                            NameEn = "ManageSites"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DescriptionAr = "عرض الهندسة",
                            DescriptionEn = "View Engineering",
                            NameAr = "عرض الهندسة",
                            NameEn = "ViewEngineering"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            DescriptionAr = "إدارة الهندسة",
                            DescriptionEn = "Manage Engineering",
                            NameAr = "إدارة الهندسة",
                            NameEn = "ManageEngineering"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            DescriptionAr = "عرض المستخدمين",
                            DescriptionEn = "View Users",
                            NameAr = "عرض المستخدمين",
                            NameEn = "ViewUsers"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333336"),
                            DescriptionAr = "إدارة المستخدمين",
                            DescriptionEn = "Manage Users",
                            NameAr = "إدارة المستخدمين",
                            NameEn = "ManageUsers"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333337"),
                            DescriptionAr = "عرض الموافقات",
                            DescriptionEn = "View Approvals",
                            NameAr = "عرض الموافقات",
                            NameEn = "ViewApprovals"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333338"),
                            DescriptionAr = "إدارة الموافقات",
                            DescriptionEn = "Manage Approvals",
                            NameAr = "إدارة الموافقات",
                            NameEn = "ManageApprovals"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333339"),
                            DescriptionAr = "عرض المالية",
                            DescriptionEn = "View Finance",
                            NameAr = "عرض المالية",
                            NameEn = "ViewFinance"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333340"),
                            DescriptionAr = "إدارة المالية",
                            DescriptionEn = "Manage Finance",
                            NameAr = "إدارة المالية",
                            NameEn = "ManageFinance"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333341"),
                            DescriptionAr = "عرض الموردين",
                            DescriptionEn = "View Vendors",
                            NameAr = "عرض الموردين",
                            NameEn = "ViewVendors"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333342"),
                            DescriptionAr = "إدارة الموردين",
                            DescriptionEn = "Manage Vendors",
                            NameAr = "إدارة الموردين",
                            NameEn = "ManageVendors"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333343"),
                            DescriptionAr = "عرض السكرتارية",
                            DescriptionEn = "View Secretary",
                            NameAr = "عرض السكرتارية",
                            NameEn = "ViewSecretary"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333344"),
                            DescriptionAr = "إدارة السكرتارية",
                            DescriptionEn = "Manage Secretary",
                            NameAr = "إدارة السكرتارية",
                            NameEn = "ManageSecretary"
                        });
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "ProjectManager"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "FinancialAnalyst"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333334")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333335")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333336")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333337")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333338")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333339")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333340")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333341")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333342")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333343")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333344")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333332")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333334")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333337")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333338")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333341")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333342")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333337")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333338")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333339")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333340")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333341")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333342")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111114"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111114"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111114"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333335")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111114"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333337")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111114"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333339")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111114"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333341")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111114"),
                            PermissionId = new Guid("33333333-3333-3333-3333-333333333343")
                        });
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.SecretaryDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecretaryDocuments");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.SecretaryInboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecretaryInboxItems");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.SecretaryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecretaryTasks");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@sasheco.com",
                            EmployeeNumber = "admin",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            Name = "admin",
                            PasswordHash = "$2a$11$O3zVCihyy0MSym1gcrABCuoez8HBLdos8JD7XxlAuxdOMxamf3wje",
                            PositionAr = "مسؤول",
                            PositionEn = "Administrator",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "engineer@sasheco.com",
                            EmployeeNumber = "ENG001",
                            FirstName = "Project",
                            IsActive = true,
                            LastName = "Engineer",
                            Name = "engineer",
                            PasswordHash = "$2a$11$O3zVCihyy0MSym1gcrABCuoez8HBLdos8JD7XxlAuxdOMxamf3wje",
                            PositionAr = "مدير مشروع",
                            PositionEn = "Project Manager",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "finance@sasheco.com",
                            EmployeeNumber = "FIN001",
                            FirstName = "Financial",
                            IsActive = true,
                            LastName = "Analyst",
                            Name = "finance",
                            PasswordHash = "$2a$11$O3zVCihyy0MSym1gcrABCuoez8HBLdos8JD7XxlAuxdOMxamf3wje",
                            PositionAr = "محلل مالي",
                            PositionEn = "Financial Analyst",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111113")
                        });
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactPersonAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ApprovalAttachment", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Approval", "Approval")
                        .WithMany("Attachments")
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approval");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Approval", "Approval")
                        .WithMany("History")
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sasheco.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approval");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Project", "Project")
                        .WithMany("Contracts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sasheco.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Contracts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ContractItem", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Contract", "Contract")
                        .WithMany("Items")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.ContractTerm", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Contract", "Contract")
                        .WithMany("Terms")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.DrawingAttachment", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Contract", "Contract")
                        .WithMany("DrawingAttachments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sasheco.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.User", b =>
                {
                    b.HasOne("Sasheco.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Approval", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("History");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Contract", b =>
                {
                    b.Navigation("DrawingAttachments");

                    b.Navigation("Items");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Project", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sasheco.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
